/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mk_training_jnicrash_HelloJNI */

#ifndef _Included_org_mk_training_jnicrash_HelloJNI
#define _Included_org_mk_training_jnicrash_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mk_training_jnicrash_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mk_training_jnicrash_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
